#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
standard_branch_regex='^(hotfix|bugfix|feature|task|refactor)\/(.*)$'
release_branch_name='^release\/([0-9]).([0-9]).([0-9])$'

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $standard_branch_regex or $release_branch_name."

if [[ ! $local_branch_name =~ $standard_branch_regex ]]; then
    if [[ ! $local_branch_name =~ $release_branch_name ]]; then
        echo $message;
        exit 1
    fi
fi

exit 0
